name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
      NCLOUD_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Check environment variables
        run: |
          if [ -z "$DB_URL" ]; then echo "DB_URL is not set"; exit 1; fi
          if [ -z "$DB_USERNAME" ]; then echo "DB_USERNAME is not set"; exit 1; fi
          if [ -z "$DB_PASSWORD" ]; then echo "DB_PASSWORD is not set"; exit 1; fi
          if [ -z "$NCLOUD_ACCESS_KEY" ]; then echo "NCLOUD_ACCESS_KEY is not set"; exit 1; fi
          if [ -z "$NCLOUD_SECRET_KEY" ]; then echo "NCLOUD_SECRET_KEY is not set"; exit 1; fi
          if [ -z "$JWT_SECRET_KEY" ]; then echo "JWT_SECRET_KEY is not set"; exit 1; fi

      - name: Build without tests
        run: ./gradlew build -x test

      - name: Run Tests
        run: ./gradlew test

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      - name: Code Quality Check - PMD
        run: ./gradlew pmdMain

      - name: Code Quality Check - SpotBugs
        run: ./gradlew spotbugsMain
